name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name acrhemanthdevsecops01

    - name: Build Docker image
      run: |
        docker build -t acrhemanthdevsecops01.azurecr.io/ops-demo:latest ./app

    - name: Push Docker image
      run: |
        docker push acrhemanthdevsecops01.azurecr.io/ops-demo:latest
